//
//  SearchImageWorker.swift
//  ImageSearcher
//
//  Created by Juliana Loaiza Labrador on 3/17/19.
//  Copyright (c) 2019 Juliana Loaiza Labrador. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SearchImageWorker {

    var imgurAPI: IImagesRepository?

    func searchImage(searchInput: SearchImage.Request, completionHandler: @escaping ([SearchImage.Response]?, NSError?) -> Void){
        imgurAPI = ImagesRepository()
        imgurAPI?.getImages(searchInput: searchInput, completionHandler: { (response, error) in
            completionHandler(response, error)
        })
    }
}
