//
//  SearchImageRouter.swift
//  ImageSearcher
//
//  Created by Juliana Loaiza Labrador on 3/17/19.
//  Copyright (c) 2019 Juliana Loaiza Labrador. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchImageRoutingLogic {
    func routeToImageDetail(segue: UIStoryboardSegue?)
}

protocol SearchImageDataPassing {
    var dataStore: SearchImageDataStore? { get }
}

class SearchImageRouter: NSObject, SearchImageRoutingLogic, SearchImageDataPassing {
    weak var viewController: SearchImageViewController?
    var dataStore: SearchImageDataStore?

    // MARK: Routing

    func routeToImageDetail(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! ImageDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            destinationVC.modalPresentationStyle = UIModalPresentationStyle.overCurrentContext
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        }
    }
    // MARK: Passing data

    func passDataToSomewhere(source: SearchImageDataStore, destination: inout ImageDetailDataStore) {
        destination.imageDetail = source.imageDetail
    }
}
