//
//  SearchImageModels.swift
//  ImageSearcher
//
//  Created by Juliana Loaiza Labrador on 3/17/19.
//  Copyright (c) 2019 Juliana Loaiza Labrador. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SearchImage {
    // MARK: Use cases

    struct Request: Codable {
        var searchInput: String
        var indexPage: Int
    }
    
    struct Data: Decodable {
        var data: [Response]
    }

    struct Response: Decodable {
        var title: String?
        var urlImage: String?

        enum CodingKeys: String, CodingKey {
            case title = "title"
            case image = "link"
        }

        init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.title = try? container.decode(String.self, forKey: .title)
            self.urlImage = try? container.decode(String.self, forKey: .image)
        }
    }

    struct ViewModel {
        var title: String?
        var urlImage: String?
        var image: UIImage?
    }
}
