//
//  SearchImagePresenter.swift
//  ImageSearcher
//
//  Created by Juliana Loaiza Labrador on 3/17/19.
//  Copyright (c) 2019 Juliana Loaiza Labrador. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchImagePresentationLogic {
    func presentImages(response: [SearchImage.Response])
    func presentImageDetail()
}

class SearchImagePresenter: SearchImagePresentationLogic {
    weak var viewController: SearchImageDisplayLogic?
    
    func presentImages(response: [SearchImage.Response]) {
        let viewModel = response.map({ SearchImage.ViewModel(title: $0.title, urlImage: $0.urlImage, image: nil)}).filter { (response) -> Bool in
            if let image = response.urlImage, image.contains(".png") {
                return true
            } else {
                return false
            }
        }

        viewController?.displayImages(viewModel: viewModel)
    }

    func presentImageDetail() {
        viewController?.displayImageDetail()
    }

}
